### ISSUE TITLE
Compilation issues with the latest Fable and F#

### ISSUE THREAD

**Issue by fc1943s** [Shmew/Fable.Extras#1]
I'm not 100% sure about what is causing it, if its Fable 3, F# 5, Feliz.CompilerPlugins or another dependency. 

![image](https://user-images.githubusercontent.com/688618/103139315-8f2e4380-46b9-11eb-8da0-b53d78011beb.png)
![image](https://user-images.githubusercontent.com/688618/103139317-948b8e00-46b9-11eb-9ec7-881a4c70bcba.png)
![image](https://user-images.githubusercontent.com/688618/103139318-96ede800-46b9-11eb-83ee-0edb4c814d20.png)

**Comment by fc1943s** [comment]
Reverting the following versions seems to fix it.

![image](https://user-images.githubusercontent.com/688618/103143078-6a07f800-46ee-11eb-9ca0-3487f7c0afff.png)

![image](https://user-images.githubusercontent.com/688618/103143073-607e9000-46ee-11eb-8324-abcfaaebc699.png)

**Comment by Shmew** [comment]
Hey @fc1943s sorry for the slow response, I've been on a bit of a vacation. This should be fixed with 0.2.4, please feel free to reopen the issue if you have any further issues. This was due to Fable.Core fixing some type definitions that I map the types in this library to for interoperability.
